# Generated by Django 5.1.4 on 2025-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='paused', max_length=20),
        ),
    ]
