# Generated by Django 5.0.3 on 2024-12-10 20:51

import django.db.models.deletion
import product.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(choices=[('item', 'Item'), ('house', 'House'), ('vehicle', 'Vehicle')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='House_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media', models.FileField(blank=True, default=None, null=True, upload_to=product.models.product_medias_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='product.product_tag'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.house_category')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_condition', models.CharField(blank=True, choices=[('new', 'New'), ('used_like_new', 'Used(Like New)'), ('used_good', 'Used(Good)'), ('used', 'Used')], max_length=30, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('meet_in_public', 'Meet in public')], default='meet_in_public', max_length=30, null=True)),
                ('availability_status', models.CharField(blank=True, choices=[('single_item', 'List as Single Item'), ('in_stock', 'List as In Stock')], default='single_item', max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.item_category')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('make', models.CharField(blank=True, max_length=80, null=True)),
                ('vehicle_condition', models.CharField(blank=True, choices=[('new', 'New'), ('used_like_new', 'Used(Like New)'), ('used_good', 'Used(Good)'), ('used', 'Used')], max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=80, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.vehicle_category')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('product.product',),
        ),
    ]
