# Generated by Django 5.0.3 on 2024-04-30 16:53

import django.db.models.deletion
import product.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.product_category'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media', models.FileField(blank=True, default=None, null=True, upload_to=product.models.product_medias_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='product.product')),
            ],
        ),
    ]
