# Generated by Django 5.0.3 on 2024-03-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='suburb',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product_location',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_location',
            name='suburb',
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Product_location',
        ),
        migrations.DeleteModel(
            name='Suburb',
        ),
    ]
