# Generated by Django 5.0.7 on 2025-02-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_sender_message_sender_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
    ]
