# Generated by Django 5.0.7 on 2025-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
